version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/cli:latest
    steps:
      - checkout
      - run: circleci policy -h
      - run:
          name: "Say hello"
          command: |
              DOMAIN=$(echo "$CIRCLE_BUILD_URL" | grep -oP '(?<=://)([^/]+)')
              echo "$DOMAIN"
              curl --request GET --url 'https://custeng-server-4.eks-dev.sphereci.com/api/v2/me' --header "Circle-Token: $CIRCLE_TOKEN"
              
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
           context: org-global
