version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run: circleci policy -h
      - run: circleci setup --no-prompt --skip-update-check --host https://custeng-server-4.eks-dev.sphereci.com --token $CIRCLECI_CLI_TOKEN
      - run: circleci policy settings --enabled=true --owner-id $ORG_ID --host https://custeng-server-4.eks-dev.sphereci.com --token $CIRCLECI_CLI_TOKEN
      #- run: circleci policy settings --owner-id $ORG_ID --host https://custeng-server-4.eks-dev.sphereci.com --token $CIRCLECI_TOKEN --policy-base-url https://custeng-server-4.eks-dev.sphereci.com
      #- run: circleci policy push ./require_jobs_checker --owner-id $ORG_ID --host https://custeng-server-4.eks-dev.sphereci.com --no-prompt --token $CIRCLE_TOKEN --policy-base-url https://custeng-server-4.eks-dev.sphereci.com
      #- run: circleci policy test ./require_jobs_checker
      - run:
          name: "Say hello"
          command: |
              DOMAIN=$(echo "$CIRCLE_BUILD_URL" | grep -oP '(?<=://)([^/]+)')
              echo "$DOMAIN"
              curl --request GET --url 'https://custeng-server-4.eks-dev.sphereci.com/api/v2/me' --header "Circle-Token: $CIRCLE_TOKEN"
              
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
           context: org-global
