version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run: circleci policy -h
      - run: circleci policy push ./require_jobs_checker --owner-id ba1c7065-b90d-4f2e-a09a-f02b1ffbbf3b --host https://custeng-server-4.eks-dev.sphereci.com --no-prompt --token $CIRCLE_TOKEN
      - run: circleci policy test ./require_jobs_checker
      - run:
          name: "Say hello"
          command: |
              DOMAIN=$(echo "$CIRCLE_BUILD_URL" | grep -oP '(?<=://)([^/]+)')
              echo "$DOMAIN"
              curl --request GET --url 'https://custeng-server-4.eks-dev.sphereci.com/api/v2/me' --header "Circle-Token: $CIRCLE_TOKEN"
              
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
           context: org-global
