version: 2.1

jobs:
  prod-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello"
      
  say-hello:
    docker:
      - image: circleci/circleci-cli:0.1.26896
    steps:
      - checkout
      - run: circleci policy -h
      - run: circleci setup --no-prompt --skip-update-check --host https://custeng-server-4.eks-dev.sphereci.com --token $CIRCLECI_CLI_TOKEN
      - run: circleci policy fetch --owner-id $ORG_ID --token $CIRCLECI_CLI_TOKEN
      #- run: circleci policy settings --owner-id $ORG_ID --host https://custeng-server-4.eks-dev.sphereci.com --token $CIRCLECI_CLI_TOKEN --policy-base-url https://custeng-server-4.eks-dev.sphereci.com
      - run: circleci policy push ./production_context_protection --owner-id $ORG_ID --host https://custeng-server-4.eks-dev.sphereci.com --no-prompt --token $CIRCLECI_CLI_TOKEN --policy-base-url https://custeng-server-4.eks-dev.sphereci.com
      - run:
          name: "Say hello"
          command: |
              DOMAIN=$(echo "$CIRCLE_BUILD_URL" | grep -oP '(?<=://)([^/]+)')
              echo "$DOMAIN"
              curl --request GET --url 'https://custeng-server-4.eks-dev.sphereci.com/api/v2/me' --header "Circle-Token: $CIRCLE_TOKEN"
              
workflows:
  say-hello-workflow:
    jobs:
      - prod-job:
           context: vault-oidc-prod
      - say-hello:
           context: org-global
           filters:
             branches:
               only:
                 - main
